version: "3.8"

services:
  postgres:
    image: postgres:14.7
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/app

  app:
    build:
      context: ./backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  celery:
    restart: always
    build:
      context: ./backend
    command: celery -A support.celery worker -l info
    volumes:
      - celery_data:/app
    depends_on:
      - redis
      - app

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - frontend:/frontend

volumes:
  postgres_data:
  redis_data:
  celery_data:
  frontend: